typedef struct pilha *Pilha;
Pilha cria_pilha();
int pilha_vazia(Pilha p);
int pilha_cheia(Pilha p);
int push(Pilha p, int elem);
int pop(Pilha p, int *elem);
int le_topo(Pilha p, int *elem);
void converte_dec_bin(int dec);
void converte_dec_octal(int dec);
void converte_dec_hexa(int dec);
