typedef struct no *Lista;
Lista cria_lista();
int lista_vazia(Lista lst);
int insere_ord(Lista *lst, int elem);
int remove_ord(Lista *lst, int elem);
void imprime_lista(Lista *lst);
int menor(Lista *lst);
int tamanho(Lista *lst);
Lista intercala(Lista *lst1, Lista *lst2, int tam1, int tam2);
int iguais(Lista *lst1, Lista *lst2);
int remove_impares(Lista *lst);
int maior(Lista *lst);
Lista concatena(Lista *lst1, Lista *lst2, int tam1, int tam2);
